options:
  config-file: ./node_modules/sass-lint-config-ctrl/.sass-lint.yml
files:
  include: 'frontend/styles/**/*.scss'
rules:
  nesting-depth: 0
  no-vendor-prefixes: 0
  property-units:
    - 2
    -
      global:
        - em
        - rem
        - s
        - vw
        - vh
